Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "public_network"
  config.vm.provision "shell", path: "./provision.sh"
end
